#ifndef _RAY_TRACING_COMMON_HPP_
#define _RAY_TRACING_COMMON_HPP_

#define RAY_TRACING_NAMESPACE_BEGIN namespace rt {
#define RAY_TRACING_NAMESPACE_END }

RAY_TRACING_NAMESPACE_BEGIN

struct Interaction;
struct Material;

RAY_TRACING_NAMESPACE_END

#endif // !_RAY_TRACING_COMMON_HPP_
